name: GitHub Actions Version Updater

# Controls when the action will run.
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.4
